// Package api_gen_code provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.0 DO NOT EDIT.
package api_gen_code

// PostReadJSONBody defines parameters for PostRead.
type PostReadJSONBody struct {
	// RequestType APIリードリクエストタイプ(ExploreCaategories, Ranking, Search)
	RequestType *string `json:"requestType,omitempty"`

	// RequestValue APIリードリクエスト値
	RequestValue *string `json:"requestValue,omitempty"`

	// UserId ユーザーID
	UserId *string `json:"userId,omitempty"`
}

// PostWriteJSONBody defines parameters for PostWrite.
type PostWriteJSONBody struct {
	// RequestType API Write RequestType:(Feed,UserRegister,SyncConfig,CodeSync,ReportActivity,Search,SubscribeSite)
	RequestType *string `json:"requestType,omitempty"`

	// RequestValue API Warite Request Value
	RequestValue *string `json:"requestValue,omitempty"`

	// Response APIレスポンス JSONデータを入れる
	Response *string `json:"response,omitempty"`

	// UserId ユーザーID
	UserId *string `json:"userId,omitempty"`
}

// PostReadJSONRequestBody defines body for PostRead for application/json ContentType.
type PostReadJSONRequestBody PostReadJSONBody

// PostWriteJSONRequestBody defines body for PostWrite for application/json ContentType.
type PostWriteJSONRequestBody PostWriteJSONBody
