// Package api_gen_code provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.0 DO NOT EDIT.
package api_gen_code

// APIResponse defines model for APIResponse.
type APIResponse struct {
	// RequestType API RequestType
	RequestType *string `json:"requestType,omitempty"`

	// ResponseValue データをjsonにして返してクライアント側で処理をする
	ResponseValue *string `json:"responseValue,omitempty"`

	// UserId ユーザーID
	UserId *string `json:"userId,omitempty"`
}

// PostReadJSONBody defines parameters for PostRead.
type PostReadJSONBody struct {
	// RequestType API Read RequestType (ExploreCategories, Ranking)
	RequestType *string `json:"requestType,omitempty"`

	// UserId ユーザーID
	UserId *string `json:"userId,omitempty"`
}

// PostSiteJSONBody defines parameters for PostSite.
type PostSiteJSONBody struct {
	// RequestArgumentJson1 API Site Request Argument 1 Value
	RequestArgumentJson1 *string `json:"requestArgumentJson1,omitempty"`

	// RequestArgumentJson2 API Site Request Argument 2 Value
	RequestArgumentJson2 *string `json:"requestArgumentJson2,omitempty"`

	// RequestType API Site RequestType
	RequestType *string `json:"requestType,omitempty"`

	// UserId ユーザーID
	UserId *string `json:"userId,omitempty"`
}

// PostUserJSONBody defines parameters for PostUser.
type PostUserJSONBody struct {
	// RequestArgumentJson1 API User Request Argument 1 Value
	RequestArgumentJson1 *string `json:"requestArgumentJson1,omitempty"`

	// RequestArgumentJson2 API User Request Argument 2 Value
	RequestArgumentJson2 *string `json:"requestArgumentJson2,omitempty"`

	// RequestType API User RequestType
	RequestType *string `json:"requestType,omitempty"`

	// UserId ユーザーID
	UserId *string `json:"userId,omitempty"`
}

// PostReadJSONRequestBody defines body for PostRead for application/json ContentType.
type PostReadJSONRequestBody PostReadJSONBody

// PostSiteJSONRequestBody defines body for PostSite for application/json ContentType.
type PostSiteJSONRequestBody PostSiteJSONBody

// PostUserJSONRequestBody defines body for PostUser for application/json ContentType.
type PostUserJSONRequestBody PostUserJSONBody
