openapi: 3.0.0

info:
  title: "Backend API"
  description: "Backend API"
  version: "1.0.0"

servers:
  - url: "http://localhost:8080"
    description: "ローカル環境"
  - url: "https://example.com"
    description: "本番環境"

tags:
  - name: "read"
    description: "DBを読み出すだけの処理"
    # externalDocs: リクエストを受け取ってDBに書き込む
  - name: "write"
    description: "リクエストを受け取ってDBに書き込む処理"

paths:
  "/read":
    post:
      # メタデータ
      tags:
        - "read"
      summary: "DBを読み出すだけの処理"
      description: "DBを読み出すだけの処理"
      deprecated: false
      # リクエスト
      requestBody:
        description: "リクエストボディ"
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  description: "ユーザーID"
                  example: "1234567890"
                requestType:
                  type: string
                  description: "APIリードリクエストタイプ(ExploreCaategories, Ranking, Search)"
                  example: "Search"
                requestValue:
                  type: string
                  description: "APIリードリクエスト値"
                  example: "ハンバーガー"
                
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: string
                    description: "ユーザーID"
                    example: "1234567890"
                  requestType:
                    type: string
                    description: "APIリードレスポンスタイプ(ExploreCaategories, Ranking, )"
                    example: "Search"
                  requestValue:
                    type: string
                    description: "APIリードリクエスト値"
                    example: "ハンバーガー"
                  response:
                    type: string
                    description: "APIレスポンス JSONデータを入れる"
                    example: "検索ならば検索結果のJSONデータを入れる"
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "エラーメッセージ"
                    example: "Bad Request"
  "/write":
    post:
      # メタデータ
      tags:
        - "write"
      summary: "リクエストを受け取ってDBに書き込む処理"
      description: "リクエストを受け取ってDBに書き込む処理"
      deprecated: false
      # リクエスト
      requestBody:
        description: "リクエストボディ"
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  description: "ユーザーID"
                  example: "1234567890"
                requestType:
                  type: string
                  description: "API Write RequestType:(Feed,UserRegister,SyncConfig,CodeSync,ReportActivity,Search,SubscribeSite)"
                  example: "Feed"
                requestValue:
                  type: string
                  description: "API Warite Request Value"
                  example: "ハンバーガー"
                response:
                  type: string
                  description: "APIレスポンス JSONデータを入れる"
                  example: "feedならばfeedリクエストのJSONデータ（サイトURL）を入れる"
                
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: string
                    description: "ユーザーID"
                    example: "1234567890"
                  requestType:
                    type: string
                    description: "API Write RequestType:(Feed,UserRegister,SyncConfig,CodeSync,ReportActivity)"
                    example: "Search"
                  requestValue:
                    type: string
                    description: "API Warite Request Value"
                    example: "ハンバーガー"
                  response:
                    type: string
                    description: "APIレスポンス JSONデータを入れる"
                    example: "検索ならば検索結果のJSONデータを入れる"
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "エラーメッセージ"
                    example: "Bad Request"

