// Package api_gen_code provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.0 DO NOT EDIT.
package api_gen_code

// APIReadResponse defines model for APIReadResponse.
type APIReadResponse struct {
	// RequestType APIリードレスポンスタイプ(ExploreCategories, Ranking, )
	RequestType *string `json:"requestType,omitempty"`

	// ResponseValue データをjsonにして返してクライアント側で処理をする
	ResponseValue *string `json:"responseValue,omitempty"`

	// UserId ユーザーID
	UserId *string `json:"userId,omitempty"`
}

// APIWriteResponse defines model for APIWriteResponse.
type APIWriteResponse struct {
	// RequestType API Write RequestType:(Feed,UserRegister,SyncConfig,CodeSync,ReportActivity)
	RequestType *string `json:"requestType,omitempty"`

	// ResponseValue APIレスポンス JSONデータを入れる
	ResponseValue *string `json:"responseValue,omitempty"`

	// UserId ユーザーID
	UserId *string `json:"userId,omitempty"`
}

// PostReadJSONBody defines parameters for PostRead.
type PostReadJSONBody struct {
	// RequestType APIリードリクエストタイプ(ExploreCategories, Ranking, Search)
	RequestType *string `json:"requestType,omitempty"`

	// RequestValue APIリードリクエスト値
	RequestValue *string `json:"requestValue,omitempty"`

	// UserId ユーザーID
	UserId *string `json:"userId,omitempty"`
}

// PostWriteJSONBody defines parameters for PostWrite.
type PostWriteJSONBody struct {
	// RequestArgumentJson1 API Write Request Argument 1 Value
	RequestArgumentJson1 *string `json:"requestArgumentJson1,omitempty"`

	// RequestArgumentJson2 API Write Request Argument 2 Value
	RequestArgumentJson2 *string `json:"requestArgumentJson2,omitempty"`

	// RequestType API Write RequestType:(Feed,UserRegister,SyncConfig,CodeSync,ReportActivity,Search,SubscribeSite)
	RequestType *string `json:"requestType,omitempty"`

	// UserId ユーザーID
	UserId *string `json:"userId,omitempty"`
}

// PostReadJSONRequestBody defines body for PostRead for application/json ContentType.
type PostReadJSONRequestBody PostReadJSONBody

// PostWriteJSONRequestBody defines body for PostWrite for application/json ContentType.
type PostWriteJSONRequestBody PostWriteJSONBody
