name: service-launch

on:
  push:
      branches:
          - master

env:
  AWS_REGION: us-east-1
  AWS_Role_ARN: secrets.IAM_ROLE_ARN
  REPO_ECR_NAME: feedays_cloud_repo

jobs:
  service_launch:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
        - name: Checkout code
          uses: actions/checkout@v2
        # ECRをデプロイ

        # ECRにログイン

        # ECRにイメージをビルド&プッシュ

        # 全てのインフラをデプロイ

        # テストクライアントのテストを実行


